config/routes.rb
Re::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  scope :module => "spree" do
    match '/products/show_variant/:id' => 'products#show_variant', :as => :show_variant_image
    match '/orders/remove_item/:id' => 'orders#remove_item', :as => :remove_item_from_cart
    match '/checkout/update_shipping_methods' => 'checkout#update_shipping_methods', :as => :update_shipping_methods
    match '/account/update_address' => 'users#update_address', :as => :update_address
    match '/account/purchase_rc' => 'users#purchase_rc', :as => :user_purchase_rc
    match '/account/change_password' => 'users#update', :as => :user_change_password
    match '/account/change_email' => 'users#update', :as => :user_change_email
  end

  resource :rowley_care_subscription, :only => [:show], :module => 'spree' do
    get :cancel
  end

  resources :orders, :module => 'spree' do
    get :as_invoice_email
    get :as_shipping_email
  end

end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :hto_settings
    resources :products do
      resources :head_turn_images do
        collection do
          post :update_positions
        end
      end
      get :add_product_on_ebay
    end
  end
end

Spree::Core::Engine.routes.prepend do
  match '/hto_checkout/registration' => 'hto_checkout#registration', :via => :get, :as => :hto_checkout_registration
  match '/hto_checkout/registration' => 'hto_checkout#update_registration', :via => :put, :as => :hto_update_checkout_registration
  put '/hto_checkout/update/:state', :to => 'hto_checkout#update', :as => :update_hto_checkout
  get '/hto_checkout/:state', :to => 'hto_checkout#edit', :as => :hto_checkout_state
  get '/hto_checkout', :to => 'hto_checkout#edit' , :as => :hto_checkout
  match '/admin' => 'admin/orders#index', :as => :admin
  match '/admin/dashboard' => 'admin/overview#index', :as => :admin_dashboard
  devise_scope :user do
    get '/cross_login/:site' => 'user_sessions#cross_login', :as => :cross_login
    get '/authenticate_by_cross_login_token' => 'user_sessions#authenticate_by_cross_login_token'
  end
end

app/views/spree/admin/images/_admin_images_listing_table.html.erb
<tbody>
      <% (@product.images + @product.variant_images).uniq.each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
          </td>
          <td><%= options_text_for(image) %></td>
          <td><%= image.alt %></td>
          <td><%= if image.try_on_photo? then t(:yes)  end rescue 'n/a' %></td>
          <td><%= if image.vto_image? then t(:yes)  end rescue 'n/a' %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-edit', t(:edit), edit_admin_product_image_url(@product, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_product_image_url(@product, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>