config/routes.rb
Re::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  scope :module => "spree" do
    match '/products/show_variant/:id' => 'products#show_variant', :as => :show_variant_image
    match '/orders/remove_item/:id' => 'orders#remove_item', :as => :remove_item_from_cart
    match '/checkout/update_shipping_methods' => 'checkout#update_shipping_methods', :as => :update_shipping_methods
    match '/account/update_address' => 'users#update_address', :as => :update_address
    match '/account/purchase_rc' => 'users#purchase_rc', :as => :user_purchase_rc
    match '/account/change_password' => 'users#update', :as => :user_change_password
    match '/account/change_email' => 'users#update', :as => :user_change_email
  end

  resource :rowley_care_subscription, :only => [:show], :module => 'spree' do
    get :cancel
  end

  resources :orders, :module => 'spree' do
    get :as_invoice_email
    get :as_shipping_email
  end

end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :hto_settings
    resources :products do
      resources :head_turn_images do
        collection do
          post :update_positions
        end
      end
      get :add_product_on_ebay
    end
  end
end

Spree::Core::Engine.routes.prepend do
  match '/hto_checkout/registration' => 'hto_checkout#registration', :via => :get, :as => :hto_checkout_registration
  match '/hto_checkout/registration' => 'hto_checkout#update_registration', :via => :put, :as => :hto_update_checkout_registration
  put '/hto_checkout/update/:state', :to => 'hto_checkout#update', :as => :update_hto_checkout
  get '/hto_checkout/:state', :to => 'hto_checkout#edit', :as => :hto_checkout_state
  get '/hto_checkout', :to => 'hto_checkout#edit' , :as => :hto_checkout
  match '/admin' => 'admin/orders#index', :as => :admin
  match '/admin/dashboard' => 'admin/overview#index', :as => :admin_dashboard
  devise_scope :user do
    get '/cross_login/:site' => 'user_sessions#cross_login', :as => :cross_login
    get '/authenticate_by_cross_login_token' => 'user_sessions#authenticate_by_cross_login_token'
  end
end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
  def authorize_admin
    authorize! :manage, Spree::Order
  end
end

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:new_order), new_admin_order_url, :icon => 'icon-plus', :id => 'admin_new_order' %>
  </li>
  <%= button_link_to t(:new_hto_order), new_admin_order_url(:hto => true), :icon => 'icon-plus', :id => 'admin_new_order' %>
<% end %>

<% content_for :table_filter_title do %>
  <%= t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field-block alpha four columns">          
        <div class="date-range-filter field">
          <%= label_tag nil, t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => t(:start) %>
            
            <span class="range-divider">
              <i class="icon-arrow-right"></i>
            </span>
              
            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => t(:stop) %>
          </div>
        </div>

        <div class="field">
          <%= label_tag nil, t(:status) %>
          <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2' %>  
        </div>
      </div>
      
      <div class="four columns">
        <div class="field">
          <%= label_tag nil, t(:order_number) %>
          <%= f.text_field :number_cont %>
        </div>
        <div class="field">
          <%= label_tag nil, t(:email) %>
          <%= f.email_field :email_cont %>
        </div>
      </div>
      
      <div class="four columns">
        <div class="field">
          <%= label_tag nil, t(:first_name_begins_with) %>
          <%= f.text_field :bill_address_firstname_start, :size => 25 %>
        </div>
        <div class="field">
          <%= label_tag nil, t(:last_name_begins_with) %>
          <%= f.text_field :bill_address_lastname_start, :size => 25%>
        </div>
      </div>
      
      <div class="omega four columns">
        <div class="field checkbox">
          <label>
            <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '' %>
            <%= t(:show_only_complete_orders) %>
          </label>
        </div>

        <div class="field checkbox">
          <label>
            <%= f.check_box :inventory_units_shipment_id_null, { }, '1', '0' %>
            <%= t(:show_only_unfulfilled_orders) %>
          </label>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button t(:filter_results), 'icon-search' %>
        </div>
      </div>
    <% end %>    
  </div>
<% end %>

<table class="index responsive" id="listing_orders" data-hook>
  <colgroup>
     <col style="width: 16%;">
     <col style="width: 10%;">
     <col style="width: 13%;">
     <col style="width: 13%;">
     <col style="width: 13%;">
     <col style="width: 17%;">
     <col style="width: 10%;">
     <col style="width: 8%;">
  </colgroup>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at,   t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% end %>
      <th><%= sort_link @search, :number,         t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :state,          t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :payment_state,  t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :shipment_state, t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :email,          t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :total,          t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
      <th data-hook="admin_orders_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
      <td class="align-center"><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
      <td><%= link_to order.number, admin_order_path(order) %></td>
      <td class="align-center"><span class="state <%= order.state.downcase %>"><%= t("order_state.#{order.state.downcase}") %></span></td>
      <td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>
      <td class="align-center"><span class="state <%= order.shipment_state %>"><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></span></td>
      <td><%= mail_to order.email %></td>
      <td class="align-center"><%= if order.hto? then Spree::Money.new(0, { :currency => order.currency }) else order.display_total end %></td>
      <td class='actions align-center' data-hook="admin_orders_index_row_actions">
        <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @orders %>