spree_lens_prescriptions/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    # resources :orders, :only => [] do
    #   get :prescription
    #   get :prescription
    # end
    resources :orders do
      resource :lens_prescription do
        get :fire
      end
      get 'prescription_to_lab' => 'orders#send_prescription_to_lab', :as => :prescription_to_lab
    end
    resources :users do
      get :cancel_subscription
    end
    resource :lens_prescription_settings
    resource :lens_prescription_uploads_settings
    resource :lens_prescription_lab_email_settings
    resource :subscription_settings
  end

  resource :subscription, :only => [:show], :module => 'lens_prescription' do
    get :cancel
  end
end

spree_lens_prescriptions/app/controllers/spree/admin/lens_prescription_lab_email_settings_controller.rb
module Spree
  module Admin
    class LensPrescriptionLabEmailSettingsController < Spree::Admin::BaseController
      def show
        redirect_to(:action => :edit)
      end

      def update
        Spree::Config.set(params[:preferences])

        respond_to do |format|
          format.html {
            flash[:notice] = t(:lens_prescription_lab_email_settings_updated)
            redirect_to edit_admin_lens_prescription_lab_email_settings_path
          }
        end
      end

    end
  end
end

spree_lens_prescriptions/app/views/spree/admin/lens_prescription_lab_email_settings/edit.html.haml
= render :partial => 'spree/admin/shared/configuration_menu'
= render :partial => 'spree/admin/shared/lens_prescription_settings_sub_menu'
= form_tag admin_lens_prescription_lab_email_settings_path, :method => :put do
  %fieldset.no-border-top
    %fieldset.no-border-bottom
      %legend{:align => "center"}= t(:lab_email_settings)
      .alpha.eight.columns
        .field{"data-hook" => "lens_prescription_lab_num"}
          = label_tag 'preferences[lp_lab_num]', t(:lp_lab_num)
          = preference_field_tag 'preferences[lp_lab_num]', Spree::Config[:lp_lab_num], :type => :string
      .alpha.eight.columns
        .field{"data-hook" => "lens_prescription_lp_customer_num"}
          = label_tag 'preferences[lp_customer_num]', t(:lp_customer_num)
          = preference_field_tag 'preferences[lp_customer_num]', Spree::Config[:lp_customer_num], :type => :string
      .alpha.eight.columns
        .field{"data-hook" => "lens_prescription_lp_lab_email"}
          = label_tag 'preferences[lp_lab_email]', t(:lp_lab_email)
          = preference_field_tag 'preferences[lp_lab_email]', Spree::Config[:lp_lab_email], :type => :string
      .alpha.eight.columns
        .field{"data-hook" => "lens_prescription_lp_lab_email_from"}
          = label_tag 'preferences[lp_lab_email_from]', t(:lp_lab_email_from)
          = preference_field_tag 'preferences[lp_lab_email_from]', Spree::Config[:lp_lab_email_from], :type => :string


    .form-buttons.filter-actions.actions{"data-hook" => "buttons"}
      = button t(:update), 'icon-refresh'