config/routes.rb
Re::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  scope :module => "spree" do
    match '/products/show_variant/:id' => 'products#show_variant', :as => :show_variant_image
    match '/orders/remove_item/:id' => 'orders#remove_item', :as => :remove_item_from_cart
    match '/checkout/update_shipping_methods' => 'checkout#update_shipping_methods', :as => :update_shipping_methods
    match '/account/update_address' => 'users#update_address', :as => :update_address
    match '/account/purchase_rc' => 'users#purchase_rc', :as => :user_purchase_rc
    match '/account/change_password' => 'users#update', :as => :user_change_password
    match '/account/change_email' => 'users#update', :as => :user_change_email
  end

  resource :rowley_care_subscription, :only => [:show], :module => 'spree' do
    get :cancel
  end

  resources :orders, :module => 'spree' do
    get :as_invoice_email
    get :as_shipping_email
  end

end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :hto_settings
    resources :products do
      resources :head_turn_images do
        collection do
          post :update_positions
        end
      end
      get :add_product_on_ebay
    end
  end
end

Spree::Core::Engine.routes.prepend do
  match '/hto_checkout/registration' => 'hto_checkout#registration', :via => :get, :as => :hto_checkout_registration
  match '/hto_checkout/registration' => 'hto_checkout#update_registration', :via => :put, :as => :hto_update_checkout_registration
  put '/hto_checkout/update/:state', :to => 'hto_checkout#update', :as => :update_hto_checkout
  get '/hto_checkout/:state', :to => 'hto_checkout#edit', :as => :hto_checkout_state
  get '/hto_checkout', :to => 'hto_checkout#edit' , :as => :hto_checkout
  match '/admin' => 'admin/orders#index', :as => :admin
  match '/admin/dashboard' => 'admin/overview#index', :as => :admin_dashboard
  devise_scope :user do
    get '/cross_login/:site' => 'user_sessions#cross_login', :as => :cross_login
    get '/authenticate_by_cross_login_token' => 'user_sessions#authenticate_by_cross_login_token'
  end
end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
  def authorize_admin
    authorize! :manage, Spree::Order
  end
end

app/views/spree/checkout/order/_order_details.html.haml
.row.steps-data
  %h5.offset-left=t(:shopping_cart)
  %table.index.table-checkout-order{"data-hook" => "order_details"}
    %tbody#line-items{"data-hook" => ""}
      - @order.line_items.each do |item|
        %tr{"data-hook" => "order_details_line_item_row"}
          %td.image-row{"data-hook" => "order_item_image"}
            - if item.variant.images.length == 0
              = link_to mini_image(item.variant.product), item.variant.product
            - else
              = link_to image_tag(item.variant.images.first.attachment.url(:mini)), item.variant.product
            .product-glasses-number.checkout-glasses-number
              %span.no NO.
              %span.glasses-no= item.variant.product.name
          %td{"data-hook" => "order_item_description"}
            .param-name=t(:item) + ':'
            .param-value
              No.
              = item.variant.product.name
          %td{"data-hook" => "order_item_color"}
            .param-name=t(:color) + ':'
            .param-value
              = item.variant.option_value('frames-color') unless item.variant.option_values.empty?
          %td{"data-hook" => "order_item_qty"}
            .param-name=t(:quantity)+':'
            .param-value
              = item.quantity
          %td.total{"data-hook" => "order_item_total"}
            .param-name=t(:amount) + ':'
            .param-value
              = item.display_amount
      - if @order.lens_meta_prescription.purchase_subscription.present?
        %tr{"data-hook" => "order_details_line_item_row"}
          %td.image-row{"data-hook" => "rowley_care_image"}
            =image_tag '/assets/store/rowley-bag.jpg'
          %td{"data-hook" => "order_item_description"}
            .param-name=t(:item) + ':'
            .param-value
              = t(:rowley_care)
          %td{"data-hook" => "order_item_color"}
            .param-name=t(:color) + ':'
            .param-value
              ='--------'
          %td{"data-hook" => "order_item_qty"}
            .param-name=t(:quantity)+':'
            .param-value
              1
          %td.total{"data-hook" => "order_item_total"}
            .param-name=t(:amount) + ':'
            .param-value
              =Spree::Money.new(@order.lens_meta_prescription.rowley_care_subscription_amount, { :currency => @order.currency })


.checkout-section.steps-data.prescription-details
  %h5
    =t(:prescription)
    %span=link_to t(:edit), checkout_state_path(:lens_prescription), :class => 'action-link'
  %div
    %p.param-value=t("lens_prescription.glasses_type.#{@order.lens_meta_prescription.glasses_type}")
    = render "spree/checkout/prescription_details/#{@order.lens_meta_prescription.glasses_type}", :prescription => @order.lens_meta_prescription.lens_prescription

.row.steps-data.offset-left
  - if order.has_step?("shipping")
    .columns.four
      %h5
        = t(:shipping_address)
        %span= link_to t(:edit), (checkout_state_path(:shipping) unless @order.completed?), :class => 'action-link'
      .address
        = order.ship_address
    .columns.alpha.four
      %h5
        = t(:billing_address)
        %span= link_to t(:edit), (checkout_state_path(:billing) unless @order.completed?), :class => 'action-link'
      .address
        = order.bill_address
    - if @order.has_step?("shipping") && order.shipping_method.present?
      .columns.alpha.four
        %h5
          = t(:shipping_method)
          %span= link_to t(:edit), (checkout_state_path(:shipping) unless @order.completed?), :class => 'action-link'
        .delivery
          = order.shipping_method.name
  .columns.omega.five
    %h5
      = t(:payment_information)
      %span= link_to t(:edit), (checkout_state_path(:billing) unless @order.completed?), :class => 'action-link'
    .payment-info
      - if order.credit_cards.empty?
        = content_tag(:span, order.payment.payment_method.name) if order.payment
      - else
        %span.cc-type
          = t(:ending_in)
          = order.credit_cards.first.last_digits
        %br/
        %span.full-name
          = order.credit_cards.first.first_name
          = order.credit_cards.first.last_name